---
# Example config for tg-archive (copy to config.yaml and edit).

api_id: ""
api_hash: ""

# Telegram channel / group name or your group username or your group id (a negative number).
group: ""

# Avatars and media will be downloaded into media_dir.
download_media: true
download_avatars: true
avatar_size: [64, 64] # Width, Height.
media_dir: "media"

# Download only these mime types (lowercase). Empty means all types.
# media_mime_types: ["video/mp4", "video/quicktime", "video/x-matroska"]
media_mime_types: []

# Topic-based filtering (forum topics).
topic_ids: []
topic_titles: []
include_general: true

# Takeout mode allows higher rate than standard mode.
use_takeout: false

proxy:
  enable: false
  protocol: "socks5"
  addr: "127.0.0.1"
  port: 1080

fetch_batch_size: 2000
fetch_wait: 5
fetch_limit: 0

publish_dir: "site"
static_dir: "static"
per_page: 500
show_day_index: true

telegram_url: "https://t.me/{id}"
show_sender_fullname: false

timezone: ""

publish_rss_feed: true
rss_feed_entries: 100

publish_media_index: false
media_pages_dir: "media-pages"
publish_media_hashtags: true
media_by_topic: false
migrate_media_by_topic: false

site_url: "https://mysite.com"
site_name: "@{group} - Telegram group archive"
site_description: "Public archive of Telegram messages."
meta_description: "@{group} {date} - Telegram message archive."
page_title: "Page {page} - {date} @{group} Telegram message archive."
